version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin

    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /conf/jellyfin:/config
      - /media/tvshows:/data/tvshows
      - /media/movies:/data/movies

    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Asia/Kolkata
       ports:
            - 5055:5055
       volumes:
            - /conf/jellyserr:/app/config
       restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    user : root
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /conf/sonarr:/config
      - /media/tvshows:/tv 
      - /media:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /conf/jackett:/config
      - /conf/jackettdownloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    user : root
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /conf/radarr:/config
      - /media/movies:/movies #optional
      - /media:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
